#ML codes to predict level of some invironmental parameters in the south delta. R programming language used.


Ion=read.csv(file.choose())
pairs(~B+Br+Ca +Cl+Hardness+K +Mg +NO3+ Na +SO4+ SpCond_ +TDS +T_Alk,data=Ion,pch = 20)
Ion$Station = as.numeric(factor(Ion$Station,levels = c('GLE', 'ORX', 'TWA','OH1','PDC','PDUP','SGA'),labels = c(1, 2, 3, 4, 5, 6, 7)))

Ion=Ion[Ion$Station !="PDC",]

#Dissolved Nitrate (NO3)

install.packages("gam")
install.packages("hydroGOF")
library(hydroGOF)
library(gam)
gam.NO3 <- gam(NO3~s(SpCond_)+s(Station), data= Ion)
plot(gam.NO3,pch = 20,resid=T)
Predicted.NO3.GAM  <-predict(gam.NO3,newdata=Ion)
(cor(Predicted.NO3.GAM,Ion[,10])^2)
GAM.MSE.NO3 <- (mean(Predicted.NO3.GAM-Ion[,10]))^2
MAE.GAM.NO3 <- (mean(abs(Predicted.NO3.GAM-Ion[,10])))
print(MAE.GAM.NO3)
Pbias.NO3.GAM <- 100*(sum(Predicted.NO3.GAM-Ion[,10])/sum(Ion[,10]))
print("Pbias =");print(Pbias.NO3.GAM)
Nash.Sutcliff.Effect.NO3.GAM= NSE(Predicted.NO3.GAM,Ion[,10])
print("NSE =");print(Nash.Sutcliff.Effect.NO3.GAM )

install.packages("rpart")
install.packages("partykit")
library(rpart)
library(partykit)
Tree.NO3 <- rpart(NO3~SpCond_+Station,data=Ion,control=rpart.control(cp=0.005,xval=50))
Predicted.NO3.Tree=predict(Tree.NO3, newdata = Ion)
plot(as.party(Tree.NO3), tp_args=list(id=FALSE))
(cor(Predicted.NO3.Tree,Ion[,10])^2)
MAE.Tree.NO3 <- (mean(abs(Predicted.NO3.Tree-Ion[,10])))
print(MAE.Tree.NO3)
Pbias.NO3.Tree <- 100*(sum(Predicted.NO3.Tree-Ion[,10])/sum(Ion[,10]))
print("Pbias =");print(Pbias.NO3.Tree)
Nash.Sutcliff.Effect.NO3.Tree= NSE(Predicted.NO3.Tree,Ion[,10])
print("NSE =");print(Nash.Sutcliff.Effect.NO3.Tree )

install.packages("randomForest")
library(randomForest)
RF.NO3 <- randomForest( formula = NO3 ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.NO3)
which.min(RF.NO3$mse)
P=varImpPlot(RF.NO3, sort=TRUE)
Predicted.NO3.RF=predict(RF.NO3,newdata = Ion)
(cor(Predicted.NO3.RF,Ion[,10])^2)
MAE.RF.NO3 <- (mean(abs(Predicted.NO3.RF-Ion[,10])))
print(MAE.RF.NO3)
Pbias.NO3.RF <- 100*(sum(Predicted.NO3.RF-Ion[,10])/sum(Ion[,10]))
print("Pbias =");print(Pbias.NO3.RF)
Nash.Sutcliff.Effect.NO3.RF= NSE(Predicted.NO3.RF,Ion[,10])
print("NSE =");print(Nash.Sutcliff.Effect.NO3.RF )

--------------------------------------------------------------------------------------------
  #Dissolved Potassium (K)
  library(hydroGOF)
library(gam)
gam.K <- gam(K~s(SpCond_)+s(Station), data= Ion)
plot(gam.K,pch = 20,resid=T)
Predicted.K.GAM  <-predict(gam.K,newdata=Ion)
(cor(Predicted.K.GAM,Ion[,8])^2)
GAM.MSE.K <- (mean(Predicted.K.GAM-Ion[,8]))^2
MAE.GAM.K <- (mean(abs(Predicted.K.GAM-Ion[,8])))
print("MAE =");print(MAE.GAM.K)
Pbias.K.GAM <- 100*(sum(Predicted.K.GAM-Ion[,8])/sum(Ion[,8]))
print("Pbias =");print(Pbias.K.GAM)
Nash.Sutcliff.Effect.K.GAM= NSE(Predicted.K.GAM,Ion[,8])
print("NSE =");print(Nash.Sutcliff.Effect.K.GAM )


library(rpart)
library(partykit)
Tree.K <- rpart(K~SpCond_+Station,data=Ion,control=rpart.control(cp=0.005,xval=50))
Predicted.K.Tree=predict(Tree.K, newdata = Ion)
plot(as.party(Tree.K), tp_args=list(id=FALSE))
(cor(Predicted.K.Tree,Ion[,8])^2)
MAE.Tree.K <- (mean(abs(Predicted.K.Tree-Ion[,8])))
print("MAE =");print(MAE.Tree.K)
Pbias.K.Tree <- 100*(sum(Predicted.K.Tree-Ion[,8])/sum(Ion[,8]))
print("Pbias =");print(Pbias.K.Tree)
Nash.Sutcliff.Effect.K.Tree= NSE(Predicted.K.Tree,Ion[,8])
print("NSE =");print(Nash.Sutcliff.Effect.K.Tree )


library(randomForest)
RF.K <- randomForest( formula = K ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.K)
which.min(RF.K$mse)
P=varImpPlot(RF.K, sort=TRUE)
Predicted.K.RF=predict(RF.K,newdata = Ion)
(cor(Predicted.K.RF,Ion[,8])^2)
MAE.RF.K <- (mean(abs(Predicted.K.RF-Ion[,8])))
print("MAE =");print(MAE.RF.K)
Pbias.K.RF <- 100*(sum(Predicted.K.RF-Ion[,8])/sum(Ion[,8]))
print("Pbias =");print(Pbias.K.RF)
Nash.Sutcliff.Effect.K.RF= NSE(Predicted.K.RF,Ion[,8])
print("NSE =");print(Nash.Sutcliff.Effect.K.RF )
---------------------------------------------------------------------------
  #Dissolved Boron   
  
  library(hydroGOF)
library(gam)
gam.B <- gam(B~s(SpCond_)+s(Station), data= Ion)
plot(gam.B,pch = 20,resid=T)
Predicted.B.GAM  <-predict(gam.B,newdata=Ion)
(cor(Predicted.B.GAM,Ion[,3])^2)
GAM.MSE.B <- (mean(Predicted.B.GAM-Ion[,3]))^2
MAE.GAM.B <- (mean(abs(Predicted.B.GAM-Ion[,3])))
print("MAE =");print(MAE.GAM.B)
Pbias.B.GAM <- 100*(sum(Predicted.B.GAM-Ion[,3])/sum(Ion[,3]))
print("Pbias =");print(Pbias.B.GAM)
Nash.Sutcliff.Effect.B.GAM= NSE(Predicted.B.GAM,Ion[,3])
print("NSE =");print(Nash.Sutcliff.Effect.B.GAM )


library(rpart)
library(partykit)
Tree.B <- rpart(B~SpCond_+Station,data=Ion,control=rpart.control(cp=0.005,xval=50))
Predicted.B.Tree=predict(Tree.B, newdata = Ion)
plot(as.party(Tree.B), tp_args=list(id=FALSE))
(cor(Predicted.B.Tree,Ion[,3])^2)
MAE.Tree.B <- (mean(abs(Predicted.B.Tree-Ion[,3])))
print("MAE =");print(MAE.Tree.B)
Pbias.B.Tree <- 100*(sum(Predicted.B.Tree-Ion[,3])/sum(Ion[,3]))
print("Pbias =");print(Pbias.B.Tree)
Nash.Sutcliff.Effect.B.Tree= NSE(Predicted.B.Tree,Ion[,3])
print("NSE =");print(Nash.Sutcliff.Effect.B.Tree )


library(randomForest)
RF.B <- randomForest( formula = B ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.B)
which.min(RF.B$mse)
P=varImpPlot(RF.B, sort=TRUE)
Predicted.B.RF=predict(RF.B,newdata = Ion)
(cor(Predicted.B.RF,Ion[,3])^2)
MAE.RF.B <- (mean(abs(Predicted.B.RF-Ion[,3])))
print("MAE =");print(MAE.RF.B)
Pbias.B.RF <- 100*(sum(Predicted.B.RF-Ion[,3])/sum(Ion[,3]))
print("Pbias =");print(Pbias.B.RF)
Nash.Sutcliff.Effect.B.RF= NSE(Predicted.B.RF,Ion[,3])
print("NSE =");print(Nash.Sutcliff.Effect.B.RF )
---------------------------------------------------------------------------------
  #Total Dissolved Solids (TDS)
  
  library(randomForest)
RF.TDS <- randomForest( formula = TDS ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.TDS)
which.min(RF.TDS$mse)
P=varImpPlot(RF.TDS, sort=TRUE)
Predicted.TDS.RF=predict(RF.TDS,newdata = Ion)
(cor(Predicted.TDS.RF,Ion[,14])^2)
MAE.RF.TDS <- (mean(abs(Predicted.TDS.RF-Ion[,14])))
print(MAE.RF.TDS)
Pbias.TDS.RF <- 100*(sum(Predicted.TDS.RF-Ion[,14])/sum(Ion[,14]))
print("Pbias =");print(Pbias.TDS.RF)
Nash.Sutcliff.Effect.TDS.RF= NSE(Predicted.TDS.RF,Ion[,14])
print("NSE =");print(Nash.Sutcliff.Effect.TDS.RF )
---------------------------------------------------------------------------------
  #Dissolved Chloride
  
  library(randomForest)
RF.CL <- randomForest( formula = Cl ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.CL)
which.min(RF.CL$mse)
P=varImpPlot(RF.CL, sort=TRUE)
Predicted.CL.RF=predict(RF.CL,newdata = Ion)
(cor(Predicted.CL.RF,Ion[,6])^2)
MAE.RF.CL <- (mean(abs(Predicted.CL.RF-Ion[,6])))
print(MAE.RF.CL)
Pbias.CL.RF <- 100*(sum(Predicted.CL.RF-Ion[,6])/sum(Ion[,6]))
print("Pbias =");print(Pbias.CL.RF)
Nash.Sutcliff.Effect.CL.RF= NSE(Predicted.CL.RF,Ion[,6])
print("NSE =");print(Nash.Sutcliff.Effect.CL.RF )
---------------------------------------------------------------------------------
  #Dissolved Sulfate (SO4)
  
  library(randomForest)
RF.SO4 <- randomForest( formula = SO4 ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.SO4)
which.min(RF.SO4$mse)
P=varImpPlot(RF.SO4, sort=TRUE)
Predicted.SO4.RF=predict(RF.SO4,newdata = Ion)
(cor(Predicted.SO4.RF,Ion[,12])^2)
MAE.RF.SO4 <- (mean(abs(Predicted.SO4.RF-Ion[,12])))
print(MAE.RF.SO4)
Pbias.SO4.RF <- 100*(sum(Predicted.SO4.RF-Ion[,12])/sum(Ion[,12]))
print("Pbias =");print(Pbias.SO4.RF)
Nash.Sutcliff.Effect.SO4.RF= NSE(Predicted.SO4.RF,Ion[,12])
print("NSE =");print(Nash.Sutcliff.Effect.SO4.RF )
-----------------------------------------------------------------------------------
  #Dissolved Sodium (Na)
  
  library(randomForest)
RF.NA <- randomForest( formula = Na ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.NA)
which.min(RF.NA$mse)
P=varImpPlot(RF.NA, sort=TRUE)
Predicted.NA.RF=predict(RF.NA,newdata = Ion)
(cor(Predicted.NA.RF,Ion[,11])^2)
MAE.RF.NA <- (mean(abs(Predicted.NA.RF-Ion[,11])))
print(MAE.RF.NA)
Pbias.NA.RF <- 100*(sum(Predicted.NA.RF-Ion[,11])/sum(Ion[,11]))
print("Pbias =");print(Pbias.NA.RF)
Nash.Sutcliff.Effect.NA.RF= NSE(Predicted.NA.RF,Ion[,11])
print("NSE =");print(Nash.Sutcliff.Effect.NA.RF )
--------------------------------------------------------------------------------
  #Dissolved Calcium (Ca)
  
  library(randomForest)
RF.CA <- randomForest( formula = Ca ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.CA)
which.min(RF.CA$mse)
P=varImpPlot(RF.CA, sort=TRUE)
Predicted.CA.RF=predict(RF.CA,newdata = Ion)
(cor(Predicted.CA.RF,Ion[,5])^2)
MAE.RF.CA <- (mean(abs(Predicted.CA.RF-Ion[,5])))
print(MAE.RF.CA)
Pbias.CA.RF <- 100*(sum(Predicted.CA.RF-Ion[,5])/sum(Ion[,5]))
print("Pbias =");print(Pbias.CA.RF)
Nash.Sutcliff.Effect.CA.RF= NSE(Predicted.CA.RF,Ion[,5])
print("NSE =");print(Nash.Sutcliff.Effect.CA.RF )
--------------------------------------------------------------------------------
  #Dissolved Magnesium (Mg)
  
  library(randomForest)
RF.MG <- randomForest( formula = Mg ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.MG)
which.min(RF.MG$mse)
P=varImpPlot(RF.MG, sort=TRUE)
Predicted.MG.RF=predict(RF.MG,newdata = Ion)
(cor(Predicted.MG.RF,Ion[,9])^2)
MAE.RF.MG <- (mean(abs(Predicted.MG.RF-Ion[,9])))
print(MAE.RF.MG)
Pbias.MG.RF <- 100*(sum(Predicted.MG.RF-Ion[,9])/sum(Ion[,9]))
print("Pbias =");print(Pbias.MG.RF)
Nash.Sutcliff.Effect.MG.RF= NSE(Predicted.MG.RF,Ion[,9])
print("NSE =");print(Nash.Sutcliff.Effect.MG.RF )
--------------------------------------------------------------------------------
  #Dissolved Bromide (Br)
  
  library(randomForest)
RF.BR <- randomForest( formula = Br ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.BR)
which.min(RF.BR$mse)
P=varImpPlot(RF.BR, sort=TRUE)
Predicted.BR.RF=predict(RF.BR,newdata = Ion)
(cor(Predicted.BR.RF,Ion[,4])^2)
MAE.RF.BR <- (mean(abs(Predicted.BR.RF-Ion[,4])))
print(MAE.RF.BR)
Pbias.BR.RF <- 100*(sum(Predicted.BR.RF-Ion[,4])/sum(Ion[,4]))
print("Pbias =");print(Pbias.BR.RF)
Nash.Sutcliff.Effect.BR.RF= NSE(Predicted.BR.RF,Ion[,4])
print("NSE =");print(Nash.Sutcliff.Effect.BR.RF )

--------------------------------------------------------------------------------
  #Hardness
  
  library(randomForest)
RF.Hardness <- randomForest( formula = Hardness ~ SpCond_+Station,mtry = 2 , data = Ion)
plot(RF.Hardness)
which.min(RF.Hardness$mse)
P=varImpPlot(RF.Hardness, sort=TRUE)
Predicted.Hardness.RF=predict(RF.Hardness,newdata = Ion)
(cor(Predicted.Hardness.RF,Ion[,7])^2)
MAE.RF.Hardness <- (mean(abs(Predicted.Hardness.RF-Ion[,7])))
print(MAE.RF.Hardness)
Pbias.Hardness.RF <- 100*(sum(Predicted.Hardness.RF-Ion[,7])/sum(Ion[,7]))
print("Pbias =");print(Pbias.Hardness.RF)
Nash.Sutcliff.Effect.Hardness.RF= NSE(Predicted.Hardness.RF,Ion[,7])
print("NSE =");print(Nash.Sutcliff.Effect.Hardness.RF )

--------------------------------------------------------------------------------
  #Alkalinity
  
  IonAlk=read.csv(file.choose())

IonAlk$Station = as.numeric(factor(IonAlk$Station,levels = c('GLE', 'ORX', 'TWA','OH1','PDC','PDUP','SGA'),labels = c(1, 2, 3, 4, 5, 6, 7)))


library(randomForest)
RF.Alk <- randomForest( formula = Alk ~ SpCond_+Station,mtry = 2 , data = IonAlk)
plot(RF.Alk)
which.min(RF.Alk$mse)
P=varImpPlot(RF.Alk, sort=TRUE)
Predicted.Alk.RF=predict(RF.Alk,newdata = IonAlk)
(cor(Predicted.Alk.RF,IonAlk[,4])^2)
MAE.RF.Alk <- (mean(abs(Predicted.Alk.RF-IonAlk[,4])))
print(MAE.RF.Alk)
Pbias.Alk.RF <- 100*(sum(Predicted.Alk.RF-IonAlk[,4])/sum(IonAlk[,4]))
print("Pbias =");print(Pbias.Alk.RF)
Nash.Sutcliff.Effect.Alk.RF= NSE(Predicted.Alk.RF,IonAlk[,4])
print("NSE =");print(Nash.Sutcliff.Effect.Alk.RF )
-------------------------------------------------------------------------------
  QE=-3.83E-5*(Ion[,13])^2+1.59E-1*Ion[,13]+12.56
(cor(QE,Ion[,15])^2)
mean(abs(QE-Ion[,15]))
100*(sum(QE-Ion[,15])/sum(Ion[,15]))
NSE(QE,Ion[,15])
----------------------------------------------------------------------------
  QE=-3.83E-5*(IonAlk[,3])^2+1.59E-1*IonAlk[,3]+12.56
(cor(QE,IonAlk[,4])^2)
mean(abs(QE-IonAlk[,4]))
100*(sum(QE-IonAlk[,4])/sum(IonAlk[,4]))
NSE(QE,IonAlk[,4])